columnSuffix: null
contentColumnType: string
fieldGroup: 747bab6b-b8b3-4693-b086-2e640e5f887f # Homepage
handle: riders
instructions: null
name: Riders
searchable: false
settings:
  contentTable: '{{%matrixcontent_riders}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
