defaultPlacement: end
enableVersioning: true
handle: stories
name: Stories
propagationMethod: all
siteSettings:
  2bb124d9-d5d5-42d1-b5bb-c8aac04a66a9: # Motoventure
    enabledByDefault: true
    hasUrls: true
    template: stories/_entry
    uriFormat: 'stories/{slug}'
type: channel
